#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1531322948                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

testflight_link                           : https://beta.askyourself.app
appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Ask Yourself Everyday                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Track any aspect of your life

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Oleg Dreyman                                
your_link                                 : https://dreyman.dev                     
your_city                                 : Kyiv                                
email_address                             : oleg@dreyman.dev
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : askyourselfapp
github_username                           : dreymonde
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Ask Yourself Questions Everyday
    description                           : Track any aspect of your life by answering questions that matter to you, everyday.
    fontawesome_icon_name                 : question-circle
    
  - title                                 : Create Your Own Questions...
    description                           : Want to reflect on your life? Your work? Your relationships? Your health? Your anxiety? No problem.
    fontawesome_icon_name                 : pencil-alt

  - title                                 : ...Or Get Inspired by Our Community
    description                           : Not sure what to ask? Select from the questions that were submitted by the members of our community.
    fontawesome_icon_name                 : globe-americas

  - title                                 : Know When Your Life Changes
    description                           : With 10-day trends, you'll know instantly when your life changes. So if the burnout is coming, you'll know first.
    fontawesome_icon_name                 : chart-line

  - title                                 : Explore Detailed Stats
    description                           : Get a beautiful view of your life by exploring detailed stats on how you answer your questions on a weekly or monthly basis.
    fontawesome_icon_name                 : poll
  
  - title                                 : Daily Reminders
    description                           : Never forget to reflect on your day - receive a daily reminder at 9:15.
    fontawesome_icon_name                 : bell

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header-water.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

exclude: [vendor]

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown